import crafttweaker.item.IItemStack;
import mods.dropt.Dropt;

var clumps = Dropt.list("gtce_clumps").priority(1);

var clump = <contenttweaker:material_part:9475> as IItemStack;
<ore:oreCopper>.add(clump);
furnace.addRecipe(<gregtech:meta_item_1:10018>, clump);



/*
 * Red Granite Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_124:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_124:13>])
    )
);


/*
 * Black Granite Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_121:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_121:14>])
    )
);


/*
 * Rhyolite Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_1:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_1:4>])
    )
);


/*
 * Andesite Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_48:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_48:15>])
    )
);


/*
 * Gabbro Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_35:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_35:5>])
    )
);


/*
 * Basalt Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_15:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_15:1>])
    )
);


/*
 * Komatiite Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_153:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_153:14>])
    )
);


/*
 * Dacite Igneous Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_98:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_cobblestone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_98:2>])
    )
);


/*
 * Gneiss Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_112:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_112:4>])
    )
);


/*
 * Eclogite Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_4:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_4:11>])
    )
);


/*
 * Marble Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_148:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_148:9>])
    )
);


/*
 * Quartzite Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_87:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_87:7>])
    )
);


/*
 * Blueschist Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_128:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_128:12>])
    )
);


/*
 * Greenschist Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_73:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_73:11>])
    )
);


/*
 * Soapstone Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_156:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_156:9>])
    )
);


/*
 * Migmatite Metamorphic Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_57:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_cobblestone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_57:14>])
    )
);


/*
 * Limestone Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_141:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_141:3>])
    )
);


/*
 * Chalk Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_3:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_3:10>])
    )
);


/*
 * Shale Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_164:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_164:6>])
    )
);


/*
 * Siltstone Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_167:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_167:14>])
    )
);


/*
 * Lignite Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_147:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_147:3>])
    )
);


/*
 * Dolomite Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_14:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_14:12>])
    )
);


/*
 * Greywacke Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_37:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_37:12>])
    )
);


/*
 * Chert Sedimentary Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_18:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_cobblestone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_18:7>])
    )
);


/*
 * Red Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_207:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_207:7>])
    )
);


/*
 * Black Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_192:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_192:11>])
    )
);


/*
 * Rhyolite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_235:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_235:0>])
    )
);


/*
 * Andesite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_194:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_194:13>])
    )
);


/*
 * Gabbro Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_410:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_410:1>])
    )
);


/*
 * Basalt Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_362:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_362:15>])
    )
);


/*
 * Komatiite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_351:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_351:4>])
    )
);


/*
 * Dacite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_343:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_343:11>])
    )
);


/*
 * Gneiss Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_280:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_280:4>])
    )
);


/*
 * Eclogite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_240:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_240:5>])
    )
);


/*
 * Marble Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_465:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_465:14>])
    )
);


/*
 * Quartzite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_335:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_335:8>])
    )
);


/*
 * Blueschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_438:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_438:4>])
    )
);


/*
 * Greenschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_469:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_469:15>])
    )
);


/*
 * Soapstone Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_242:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_242:14>])
    )
);


/*
 * Migmatite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_199:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_199:13>])
    )
);


/*
 * Limestone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_443:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_443:6>])
    )
);


/*
 * Chalk Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_451:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_451:5>])
    )
);


/*
 * Shale Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_260:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_260:0>])
    )
);


/*
 * Siltstone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_295:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_295:13>])
    )
);


/*
 * Lignite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_251:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_251:3>])
    )
);


/*
 * Dolomite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_490:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_490:0>])
    )
);


/*
 * Greywacke Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_439:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_439:10>])
    )
);


/*
 * Chert Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_242:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_242:6>])
    )
);


/*
 * Red Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_351:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_351:2>])
    )
);


/*
 * Black Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_447:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_447:14>])
    )
);


/*
 * Rhyolite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_298:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_298:14>])
    )
);


/*
 * Andesite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_303:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_303:10>])
    )
);


/*
 * Gabbro Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_354:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_354:15>])
    )
);


/*
 * Basalt Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_477:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_477:10>])
    )
);


/*
 * Komatiite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_455:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_455:15>])
    )
);


/*
 * Dacite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_399:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_399:13>])
    )
);


/*
 * Gneiss Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_465:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_465:4>])
    )
);


/*
 * Eclogite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_346:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_346:5>])
    )
);


/*
 * Marble Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_293:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_293:15>])
    )
);


/*
 * Quartzite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_211:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_211:3>])
    )
);


/*
 * Blueschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_468:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_468:7>])
    )
);


/*
 * Greenschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_282:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_282:11>])
    )
);


/*
 * Soapstone Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_491:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_491:1>])
    )
);


/*
 * Migmatite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_173:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_173:14>])
    )
);


/*
 * Limestone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_315:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_315:7>])
    )
);


/*
 * Chalk Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_245:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_245:2>])
    )
);


/*
 * Shale Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_296:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_296:8>])
    )
);


/*
 * Siltstone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_275:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_275:7>])
    )
);


/*
 * Lignite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_426:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_426:14>])
    )
);


/*
 * Dolomite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_442:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_442:2>])
    )
);


/*
 * Greywacke Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_325:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_325:6>])
    )
);


/*
 * Chert Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_423:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_423:1>])
    )
);


/*
 * Quark Elder Prismarine
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_532:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<quark:elder_prismarine>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_532:7>])
    )
);


/*
 * Earthworks Slate Green
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_514:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<earthworks:block_slate_green>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_514:5>])
    )
);


/*
 * Earthworks Block Slate
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_530:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<earthworks:block_slate>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_530:3>])
    )
);


/*
 * Earthworks Slate Purple
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_532:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<earthworks:block_slate_purple>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_532:9>])
    )
);


/*
 * Rustic Slate
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_506:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<rustic:slate>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_506:7>])
    )
);


/*
 * Quark Icy Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_552:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<quark:biome_cobblestone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_552:14>])
    )
);


/*
 * Quark Fire Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_553:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<quark:biome_cobblestone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_553:5>])
    )
);


/*
 * Cobblestone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:cobblestone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:0>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:1>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:2>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:3>])
    )
);


/*
 * Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:gravel>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:4>])
    )
);


/*
 * Netherrack
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:netherrack>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:6>])
    )
);


/*
 * End Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:end_stone>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:7>])
    )
);


/*
 * Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:8>])
    )
);


/*
 * Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_copper_0:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_copper_0:9>])
    )
);

