import crafttweaker.item.IItemStack;
import mods.dropt.Dropt;

var clumps = Dropt.list("gtce_clumps").priority(1);

var clump = <materialpart:pyrite:clump>.getItemStack() as IItemStack;
<ore:orePyrite>.add(clump);
furnace.addRecipe(<minecraft:iron_ingot:0>, clump);



/*
 * Red Granite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_168:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_168:11>])
    )
);


/*
 * Black Granite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_110:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_110:3>])
    )
);


/*
 * Rhyolite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_126:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_126:13>])
    )
);


/*
 * Andesite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_63:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_63:11>])
    )
);


/*
 * Gabbro Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_153:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_153:4>])
    )
);


/*
 * Basalt Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_166:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_166:1>])
    )
);


/*
 * Komatiite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_112:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_112:14>])
    )
);


/*
 * Dacite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_151:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_151:8>])
    )
);


/*
 * Gneiss Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_87:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_87:4>])
    )
);


/*
 * Eclogite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_97:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_97:10>])
    )
);


/*
 * Marble Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_7:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_7:10>])
    )
);


/*
 * Quartzite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_133:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_133:0>])
    )
);


/*
 * Blueschist Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_42:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_42:15>])
    )
);


/*
 * Greenschist Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_148:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_148:1>])
    )
);


/*
 * Soapstone Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_129:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_129:11>])
    )
);


/*
 * Migmatite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_172:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_172:5>])
    )
);


/*
 * Limestone Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_78:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_78:12>])
    )
);


/*
 * Chalk Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_142:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_142:7>])
    )
);


/*
 * Shale Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_112:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_112:11>])
    )
);


/*
 * Siltstone Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_28:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_28:2>])
    )
);


/*
 * Lignite Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_42:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_42:0>])
    )
);


/*
 * Dolomite Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_71:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_71:1>])
    )
);


/*
 * Greywacke Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_143:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_143:15>])
    )
);


/*
 * Chert Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_145:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_145:5>])
    )
);


/*
 * Red Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_199:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_199:2>])
    )
);


/*
 * Black Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_377:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_377:6>])
    )
);


/*
 * Rhyolite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_302:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_302:11>])
    )
);


/*
 * Andesite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_174:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_174:15>])
    )
);


/*
 * Gabbro Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_334:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_334:0>])
    )
);


/*
 * Basalt Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_465:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_465:2>])
    )
);


/*
 * Komatiite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_333:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_333:5>])
    )
);


/*
 * Dacite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_453:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_453:13>])
    )
);


/*
 * Gneiss Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_187:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_187:5>])
    )
);


/*
 * Eclogite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_438:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_438:3>])
    )
);


/*
 * Marble Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_370:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_370:2>])
    )
);


/*
 * Quartzite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_243:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_243:9>])
    )
);


/*
 * Blueschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_464:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_464:0>])
    )
);


/*
 * Greenschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_455:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_455:0>])
    )
);


/*
 * Soapstone Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_336:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_336:10>])
    )
);


/*
 * Migmatite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_456:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_456:9>])
    )
);


/*
 * Limestone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_409:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_409:11>])
    )
);


/*
 * Chalk Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_481:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_481:1>])
    )
);


/*
 * Shale Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_208:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_208:9>])
    )
);


/*
 * Siltstone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_458:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_458:1>])
    )
);


/*
 * Lignite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_456:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_456:2>])
    )
);


/*
 * Dolomite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_255:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_255:2>])
    )
);


/*
 * Greywacke Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_175:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_175:6>])
    )
);


/*
 * Chert Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_209:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_209:8>])
    )
);


/*
 * Red Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_254:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_254:14>])
    )
);


/*
 * Black Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_476:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_476:3>])
    )
);


/*
 * Rhyolite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_362:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_362:0>])
    )
);


/*
 * Andesite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_394:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_394:11>])
    )
);


/*
 * Gabbro Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_283:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_283:6>])
    )
);


/*
 * Basalt Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_380:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_380:15>])
    )
);


/*
 * Komatiite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_415:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_415:5>])
    )
);


/*
 * Dacite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_219:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_219:7>])
    )
);


/*
 * Gneiss Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_402:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_402:2>])
    )
);


/*
 * Eclogite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_437:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_437:1>])
    )
);


/*
 * Marble Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_178:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_178:11>])
    )
);


/*
 * Quartzite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_226:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_226:4>])
    )
);


/*
 * Blueschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_236:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_236:8>])
    )
);


/*
 * Greenschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_180:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_180:8>])
    )
);


/*
 * Soapstone Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_367:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_367:0>])
    )
);


/*
 * Migmatite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_174:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_174:10>])
    )
);


/*
 * Limestone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_395:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_395:3>])
    )
);


/*
 * Chalk Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_285:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_285:2>])
    )
);


/*
 * Shale Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_338:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_338:10>])
    )
);


/*
 * Siltstone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_452:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_452:10>])
    )
);


/*
 * Lignite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_183:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_183:2>])
    )
);


/*
 * Dolomite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_496:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_496:9>])
    )
);


/*
 * Greywacke Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_197:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_197:10>])
    )
);


/*
 * Chert Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_215:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:pyrite:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_215:12>])
    )
);

