import crafttweaker.item.IItemStack;
import mods.dropt.Dropt;

var clumps = Dropt.list("gtce_clumps").priority(1);

var clump = <contenttweaker:material_part:9442> as IItemStack;
<ore:oreUranium>.add(clump);
furnace.addRecipe(<gregtech:meta_item_1:10075>, clump);



/*
 * Red Granite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_95:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_95:15>])
    )
);


/*
 * Black Granite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_33:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_33:15>])
    )
);


/*
 * Rhyolite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_35:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_35:10>])
    )
);


/*
 * Andesite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_25:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_25:15>])
    )
);


/*
 * Gabbro Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_60:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_60:14>])
    )
);


/*
 * Basalt Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_112:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_112:0>])
    )
);


/*
 * Komatiite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_110:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_110:10>])
    )
);


/*
 * Dacite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_57:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_57:2>])
    )
);


/*
 * Gneiss Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_123:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_123:8>])
    )
);


/*
 * Eclogite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_169:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_169:7>])
    )
);


/*
 * Marble Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_32:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_32:13>])
    )
);


/*
 * Quartzite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_50:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_50:3>])
    )
);


/*
 * Blueschist Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_131:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_131:15>])
    )
);


/*
 * Greenschist Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_98:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_98:5>])
    )
);


/*
 * Soapstone Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_128:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_128:1>])
    )
);


/*
 * Migmatite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_79:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_79:3>])
    )
);


/*
 * Limestone Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_164:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_164:4>])
    )
);


/*
 * Chalk Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_170:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_170:9>])
    )
);


/*
 * Shale Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_54:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_54:15>])
    )
);


/*
 * Siltstone Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_145:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_145:12>])
    )
);


/*
 * Lignite Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_64:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_64:0>])
    )
);


/*
 * Dolomite Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_79:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_79:1>])
    )
);


/*
 * Greywacke Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_58:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_58:12>])
    )
);


/*
 * Chert Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_130:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_130:4>])
    )
);


/*
 * Red Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_501:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_501:11>])
    )
);


/*
 * Black Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_381:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_381:0>])
    )
);


/*
 * Rhyolite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_457:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_457:0>])
    )
);


/*
 * Andesite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_251:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_251:1>])
    )
);


/*
 * Gabbro Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_492:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_492:8>])
    )
);


/*
 * Basalt Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_365:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_365:11>])
    )
);


/*
 * Komatiite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_467:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_467:12>])
    )
);


/*
 * Dacite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_302:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_302:6>])
    )
);


/*
 * Gneiss Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_474:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_474:3>])
    )
);


/*
 * Eclogite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_222:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_222:2>])
    )
);


/*
 * Marble Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_175:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_175:12>])
    )
);


/*
 * Quartzite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_256:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_256:0>])
    )
);


/*
 * Blueschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_284:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_284:1>])
    )
);


/*
 * Greenschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_277:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_277:13>])
    )
);


/*
 * Soapstone Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_492:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_492:5>])
    )
);


/*
 * Migmatite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_287:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_287:6>])
    )
);


/*
 * Limestone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_396:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_396:2>])
    )
);


/*
 * Chalk Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_367:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_367:8>])
    )
);


/*
 * Shale Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_347:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_347:0>])
    )
);


/*
 * Siltstone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_264:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_264:4>])
    )
);


/*
 * Lignite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_459:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_459:15>])
    )
);


/*
 * Dolomite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_468:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_468:12>])
    )
);


/*
 * Greywacke Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_237:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_237:9>])
    )
);


/*
 * Chert Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_330:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_330:10>])
    )
);


/*
 * Red Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_222:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_222:4>])
    )
);


/*
 * Black Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_390:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_390:1>])
    )
);


/*
 * Rhyolite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_185:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_185:2>])
    )
);


/*
 * Andesite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_177:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_177:2>])
    )
);


/*
 * Gabbro Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_426:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_426:5>])
    )
);


/*
 * Basalt Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_385:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_385:10>])
    )
);


/*
 * Komatiite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_419:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_419:7>])
    )
);


/*
 * Dacite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_238:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_238:15>])
    )
);


/*
 * Gneiss Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_422:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_422:15>])
    )
);


/*
 * Eclogite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_340:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_340:14>])
    )
);


/*
 * Marble Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_256:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_256:8>])
    )
);


/*
 * Quartzite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_254:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_254:7>])
    )
);


/*
 * Blueschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_202:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_202:12>])
    )
);


/*
 * Greenschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_214:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_214:12>])
    )
);


/*
 * Soapstone Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_347:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_347:6>])
    )
);


/*
 * Migmatite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_242:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_242:15>])
    )
);


/*
 * Limestone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_393:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_393:11>])
    )
);


/*
 * Chalk Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_317:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_317:1>])
    )
);


/*
 * Shale Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_275:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_275:8>])
    )
);


/*
 * Siltstone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_438:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_438:11>])
    )
);


/*
 * Lignite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_347:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_347:5>])
    )
);


/*
 * Dolomite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_316:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_316:0>])
    )
);


/*
 * Greywacke Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_221:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_221:4>])
    )
);


/*
 * Chert Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_444:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_444:14>])
    )
);


/*
 * Quark Elder Prismarine
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_536:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<quark:elder_prismarine>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_536:2>])
    )
);


/*
 * Earthworks Slate Green
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_528:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<earthworks:block_slate_green>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_528:5>])
    )
);


/*
 * Earthworks Block Slate
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_521:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<earthworks:block_slate>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_521:8>])
    )
);


/*
 * Earthworks Slate Purple
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_519:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<earthworks:block_slate_purple>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_519:0>])
    )
);


/*
 * Rustic Slate
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_531:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<rustic:slate>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_531:13>])
    )
);


/*
 * Quark Icy Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_544:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<quark:biome_cobblestone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_544:8>])
    )
);


/*
 * Quark Fire Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_544:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<quark:biome_cobblestone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_544:4>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:0>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:1>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:2>])
    )
);


/*
 * Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:3>])
    )
);


/*
 * Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:gravel>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:4>])
    )
);


/*
 * Netherrack
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:netherrack>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:6>])
    )
);


/*
 * End Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:end_stone>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:7>])
    )
);


/*
 * Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:8>])
    )
);


/*
 * Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["gregtech:ore_uranium_0:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([clump], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([clump], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<minecraft:sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<gregtech:ore_uranium_0:9>])
    )
);

