import crafttweaker.item.IItemStack;
import mods.dropt.Dropt;

var clumps = Dropt.list("gtce_clumps").priority(1);

var clump = <materialpart:uranium235:clump>.getItemStack() as IItemStack;
<ore:oreUranium235>.add(clump);
furnace.addRecipe(<gregtech:meta_item_1:10076>, clump);



/*
 * Red Granite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_76:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_76:2>])
    )
);


/*
 * Black Granite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_26:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_26:15>])
    )
);


/*
 * Rhyolite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_117:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_117:11>])
    )
);


/*
 * Andesite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_142:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_142:9>])
    )
);


/*
 * Gabbro Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_25:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_25:7>])
    )
);


/*
 * Basalt Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_76:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_76:11>])
    )
);


/*
 * Komatiite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_5:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_5:7>])
    )
);


/*
 * Dacite Igneous Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_49:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_49:11>])
    )
);


/*
 * Gneiss Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_157:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_157:2>])
    )
);


/*
 * Eclogite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_86:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_86:1>])
    )
);


/*
 * Marble Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_86:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_86:8>])
    )
);


/*
 * Quartzite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_35:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_35:1>])
    )
);


/*
 * Blueschist Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_40:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_40:15>])
    )
);


/*
 * Greenschist Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_36:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_36:4>])
    )
);


/*
 * Soapstone Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_15:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_15:12>])
    )
);


/*
 * Migmatite Metamorphic Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_106:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_106:1>])
    )
);


/*
 * Limestone Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_116:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_116:15>])
    )
);


/*
 * Chalk Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_74:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_74:4>])
    )
);


/*
 * Shale Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_155:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_155:5>])
    )
);


/*
 * Siltstone Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_37:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_37:3>])
    )
);


/*
 * Lignite Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_4:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_4:0>])
    )
);


/*
 * Dolomite Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_94:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_94:0>])
    )
);


/*
 * Greywacke Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_72:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_72:7>])
    )
);


/*
 * Chert Sedimentary Stone
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_71:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_stone:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_71:0>])
    )
);


/*
 * Red Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_231:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_231:0>])
    )
);


/*
 * Black Granite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_274:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_274:5>])
    )
);


/*
 * Rhyolite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_376:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_376:6>])
    )
);


/*
 * Andesite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_263:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_263:10>])
    )
);


/*
 * Gabbro Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_380:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_380:14>])
    )
);


/*
 * Basalt Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_421:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_421:2>])
    )
);


/*
 * Komatiite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_319:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_319:5>])
    )
);


/*
 * Dacite Igneous Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_385:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_385:8>])
    )
);


/*
 * Gneiss Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_481:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_481:4>])
    )
);


/*
 * Eclogite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_186:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_186:13>])
    )
);


/*
 * Marble Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_179:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_179:2>])
    )
);


/*
 * Quartzite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_458:12"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_458:12>])
    )
);


/*
 * Blueschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_402:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_402:6>])
    )
);


/*
 * Greenschist Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_331:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_331:6>])
    )
);


/*
 * Soapstone Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_262:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_262:8>])
    )
);


/*
 * Migmatite Metamorphic Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_474:13"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_474:13>])
    )
);


/*
 * Limestone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_408:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_408:9>])
    )
);


/*
 * Chalk Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_401:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_401:10>])
    )
);


/*
 * Shale Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_449:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_449:15>])
    )
);


/*
 * Siltstone Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_499:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_499:6>])
    )
);


/*
 * Lignite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_386:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_386:0>])
    )
);


/*
 * Dolomite Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_207:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_207:5>])
    )
);


/*
 * Greywacke Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_318:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_318:7>])
    )
);


/*
 * Chert Sedimentary Gravel
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_297:11"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_gravel:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_297:11>])
    )
);


/*
 * Red Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_398:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_398:5>])
    )
);


/*
 * Black Granite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_261:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_261:15>])
    )
);


/*
 * Rhyolite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_255:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_255:15>])
    )
);


/*
 * Andesite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_180:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_180:10>])
    )
);


/*
 * Gabbro Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_491:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_491:14>])
    )
);


/*
 * Basalt Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_338:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_338:1>])
    )
);


/*
 * Komatiite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_446:15"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_446:15>])
    )
);


/*
 * Dacite Igneous Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_299:8"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:igneous_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_299:8>])
    )
);


/*
 * Gneiss Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_276:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_276:14>])
    )
);


/*
 * Eclogite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_388:0"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_388:0>])
    )
);


/*
 * Marble Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_483:14"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_483:14>])
    )
);


/*
 * Quartzite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_264:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_264:1>])
    )
);


/*
 * Blueschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_210:3"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_210:3>])
    )
);


/*
 * Greenschist Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_219:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_219:6>])
    )
);


/*
 * Soapstone Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_500:9"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_500:9>])
    )
);


/*
 * Migmatite Metamorphic Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_456:6"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:metamorphic_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_456:6>])
    )
);


/*
 * Limestone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_362:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:0>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_362:10>])
    )
);


/*
 * Chalk Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_290:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:1>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_290:5>])
    )
);


/*
 * Shale Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_424:4"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:2>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_424:4>])
    )
);


/*
 * Siltstone Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_412:5"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:3>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_412:5>])
    )
);


/*
 * Lignite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_419:2"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:4>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_419:2>])
    )
);


/*
 * Dolomite Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_314:7"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:5>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_314:7>])
    )
);


/*
 * Greywacke Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_314:1"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:6>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_314:1>])
    )
);


/*
 * Chert Sedimentary Sand
 */
clumps.add(Dropt.rule()
    .matchBlocks(["contenttweaker:sub_block_holder_373:10"])
    .dropStrategy("UNIQUE")
    .dropCount(Dropt.range(5))
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 1)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 2)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 3)
        .items([<materialpart:uranium235:clump>.getItemStack()], Dropt.range(0,1))
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "EXCLUDED", 0)
        .items([<undergroundbiomes:sedimentary_sand:7>])
    )
    .addDrop(Dropt.drop()
        .selector(Dropt.weight(1), "REQUIRED")
        .items([<contenttweaker:sub_block_holder_373:10>])
    )
);

