import crafttweaker.oredict.IOreDictEntry;
oreDict.oreGtExcavatorOreApatiteOverworld.add(<gregtech:ore_apatite_0:0>);
oreDict.oreGtExcavatorOrePhosphorOverworld.add(<gregtech:ore_phosphor_0:0>);
oreDict.oreGtExcavatorOreBauxiteOverworld.add(<gregtech:ore_bauxite_0:0>);
oreDict.oreGtExcavatorOreAluminiumOverworld.add(<gregtech:ore_aluminium_0:0>);
oreDict.oreGtExcavatorOreIlmeniteOverworld.add(<gregtech:ore_ilmenite_0:0>);
oreDict.oreGtExcavatorOreRutileOverworld.add(<gregtech:ore_rutile_0:0>);
oreDict.oreGtExcavatorOreBerylliumOverworld.add(<gregtech:ore_beryllium_0:0>);
oreDict.oreGtExcavatorOreEmeraldOverworld.add(<gregtech:ore_emerald_0:0>);
oreDict.oreGtExcavatorOreThoriumOverworld.add(<gregtech:ore_thorium_0:0>);
oreDict.oreGtExcavatorOreBorniteOverworld.add(<gregtech:ore_bornite_0:0>);
oreDict.oreGtExcavatorOreChalcociteOverworld.add(<gregtech:ore_chalcocite_0:0>);
oreDict.oreGtExcavatorOreEnargiteOverworld.add(<gregtech:ore_enargite_0:0>);
oreDict.oreGtExcavatorOreCopperOverworld.add(<gregtech:ore_copper_0:0>);
oreDict.oreGtExcavatorOreChalcopyriteOverworld.add(<gregtech:ore_chalcopyrite_0:0>);
oreDict.oreGtExcavatorOreIronOverworld.add(<gregtech:ore_iron_0:0>);
oreDict.oreGtExcavatorOrePyriteOverworld.add(<gregtech:ore_pyrite_0:0>);
oreDict.oreGtExcavatorOreLigniteOverworld.add(<gregtech:ore_lignite_0:0>);
oreDict.oreGtExcavatorOreCoalOverworld.add(<gregtech:ore_coal_0:0>);
oreDict.oreGtExcavatorOreGraphiteOverworld.add(<gregtech:ore_graphite_0:0>);
oreDict.oreGtExcavatorOreDiamondOverworld.add(<gregtech:ore_diamond_0:0>);
oreDict.oreGtExcavatorOreGalenaOverworld.add(<gregtech:ore_galena_0:0>);
oreDict.oreGtExcavatorOreSilverOverworld.add(<gregtech:ore_silver_0:0>);
oreDict.oreGtExcavatorOreLeadOverworld.add(<gregtech:ore_lead_0:0>);
oreDict.oreGtExcavatorOreBrownLimoniteOverworld.add(<gregtech:ore_brown_limonite_0:0>);
oreDict.oreGtExcavatorOreYellowLimoniteOverworld.add(<gregtech:ore_yellow_limonite_0:0>);
oreDict.oreGtExcavatorOreBandedIronOverworld.add(<gregtech:ore_banded_iron_0:0>);
oreDict.oreGtExcavatorOreMalachiteOverworld.add(<gregtech:ore_malachite_0:0>);
oreDict.oreGtExcavatorOreLazuriteOverworld.add(<gregtech:ore_lazurite_0:0>);
oreDict.oreGtExcavatorOreSodaliteOverworld.add(<gregtech:ore_sodalite_0:0>);
oreDict.oreGtExcavatorOreLapisOverworld.add(<gregtech:ore_lapis_0:0>);
oreDict.oreGtExcavatorOreCalciteOverworld.add(<gregtech:ore_calcite_0:0>);
oreDict.oreGtExcavatorOreMagnetiteOverworld.add(<gregtech:ore_magnetite_0:0>);
oreDict.oreGtExcavatorOreVanadiumMagnetiteOverworld.add(<gregtech:ore_vanadium_magnetite_0:0>);
oreDict.oreGtExcavatorOreGoldOverworld.add(<gregtech:ore_gold_0:0>);
oreDict.oreGtExcavatorOreGrossularOverworld.add(<gregtech:ore_grossular_0:0>);
oreDict.oreGtExcavatorOreSpessartineOverworld.add(<gregtech:ore_spessartine_0:0>);
oreDict.oreGtExcavatorOrePyrolusiteOverworld.add(<gregtech:ore_pyrolusite_0:0>);
oreDict.oreGtExcavatorOreTantaliteOverworld.add(<gregtech:ore_tantalite_0:0>);
oreDict.oreGtExcavatorOreWulfeniteOverworld.add(<gregtech:ore_wulfenite_0:0>);
oreDict.oreGtExcavatorOreMolybdeniteOverworld.add(<gregtech:ore_molybdenite_0:0>);
oreDict.oreGtExcavatorOrePowelliteOverworld.add(<gregtech:ore_powellite_0:0>);
oreDict.oreGtExcavatorOreBastnasiteOverworld.add(<gregtech:ore_bastnasite_0:0>);
oreDict.oreGtExcavatorOreMonaziteOverworld.add(<gregtech:ore_monazite_0:0>);
oreDict.oreGtExcavatorOreNeodymiumOverworld.add(<gregtech:ore_neodymium_0:0>);
oreDict.oreGtExcavatorOreGarnieriteOverworld.add(<gregtech:ore_garnierite_0:0>);
oreDict.oreGtExcavatorOreNickelOverworld.add(<gregtech:ore_nickel_0:0>);
oreDict.oreGtExcavatorOreCobaltiteOverworld.add(<gregtech:ore_cobaltite_0:0>);
oreDict.oreGtExcavatorOrePentlanditeOverworld.add(<gregtech:ore_pentlandite_0:0>);
oreDict.oreGtExcavatorOreBentoniteOverworld.add(<gregtech:ore_bentonite_0:0>);
oreDict.oreGtExcavatorOreMagnesiteOverworld.add(<gregtech:ore_magnesite_0:0>);
oreDict.oreGtExcavatorOreOlivineOverworld.add(<gregtech:ore_olivine_0:0>);
oreDict.oreGtExcavatorOreGlauconiteOverworld.add(<gregtech:ore_glauconite_0:0>);
oreDict.oreGtExcavatorOrePitchblendeOverworld.add(<gregtech:ore_pitchblende_0:0>);
oreDict.oreGtExcavatorOreUraniniteOverworld.add(<gregtech:ore_uraninite_0:0>);
oreDict.oreGtExcavatorOreUraniumOverworld.add(<gregtech:ore_uranium_0:0>);
oreDict.oreGtExcavatorOrePlatinumOverworld.add(<gregtech:ore_platinum_0:0>);
oreDict.oreGtExcavatorOrePalladiumOverworld.add(<gregtech:ore_palladium_0:0>);
oreDict.oreGtExcavatorOreIridiumOverworld.add(<gregtech:ore_iridium_0:0>);
oreDict.oreGtExcavatorOreQuartziteOverworld.add(<gregtech:ore_quartzite_0:0>);
oreDict.oreGtExcavatorOreBariteOverworld.add(<gregtech:ore_barite_0:0>);
oreDict.oreGtExcavatorOreCertusQuartzOverworld.add(<gregtech:ore_certus_quartz_0:0>);
oreDict.oreGtExcavatorOreTennantiteOverworld.add(<gregtech:ore_tennantite_0:0>);
oreDict.oreGtExcavatorOreRedstoneOverworld.add(<gregtech:ore_redstone_0:0>);
oreDict.oreGtExcavatorOreRubyOverworld.add(<gregtech:ore_ruby_0:0>);
oreDict.oreGtExcavatorOreCinnabarOverworld.add(<gregtech:ore_cinnabar_0:0>);
oreDict.oreGtExcavatorOreChromiteOverworld.add(<gregtech:ore_chromite_0:0>);
oreDict.oreGtExcavatorOreSaltOverworld.add(<gregtech:ore_salt_0:0>);
oreDict.oreGtExcavatorOreRockSaltOverworld.add(<gregtech:ore_rock_salt_0:0>);
oreDict.oreGtExcavatorOreLepidoliteOverworld.add(<gregtech:ore_lepidolite_0:0>);
oreDict.oreGtExcavatorOreSpodumeneOverworld.add(<gregtech:ore_spodumene_0:0>);
oreDict.oreGtExcavatorOreAlmandineOverworld.add(<gregtech:ore_almandine_0:0>);
oreDict.oreGtExcavatorOrePyropeOverworld.add(<gregtech:ore_pyrope_0:0>);
oreDict.oreGtExcavatorOreSapphireOverworld.add(<gregtech:ore_sapphire_0:0>);
oreDict.oreGtExcavatorOreGreenSapphireOverworld.add(<gregtech:ore_green_sapphire_0:0>);
oreDict.oreGtExcavatorOreSoapstoneOverworld.add(<gregtech:ore_soapstone_0:0>);
oreDict.oreGtExcavatorOreTalcOverworld.add(<gregtech:ore_talc_0:0>);
oreDict.oreGtExcavatorOreTenoriteOverworld.add(<gregtech:ore_tenorite_0:0>);
oreDict.oreGtExcavatorOreCupriteOverworld.add(<gregtech:ore_cuprite_0:0>);
oreDict.oreGtExcavatorOreTetrahedriteOverworld.add(<gregtech:ore_tetrahedrite_0:0>);
oreDict.oreGtExcavatorOreStibniteOverworld.add(<gregtech:ore_stibnite_0:0>);
oreDict.oreGtExcavatorOreTinOverworld.add(<gregtech:ore_tin_0:0>);
oreDict.oreGtExcavatorOreCassiteriteOverworld.add(<gregtech:ore_cassiterite_0:0>);
oreDict.oreGtExcavatorOreScheeliteOverworld.add(<gregtech:ore_scheelite_0:0>);
oreDict.oreGtExcavatorOreTungstateOverworld.add(<gregtech:ore_tungstate_0:0>);
oreDict.oreGtExcavatorOreLithiumOverworld.add(<gregtech:ore_lithium_0:0>);
mods.immersiveengineering.Excavator.addMineral("Apatite", 60, 0.005, ["oreGtExcavatorOreApatiteOverworld", "oreGtExcavatorOrePhosphorOverworld"], [0.36,0.24], [0]);
mods.immersiveengineering.Excavator.addMineral("Bauxite", 90, 0.005, ["oreGtExcavatorOreBauxiteOverworld", "oreGtExcavatorOreAluminiumOverworld", "oreGtExcavatorOreIlmeniteOverworld", "oreGtExcavatorOreRutileOverworld"], [0.48,0.24,0.12,0.02], [0]);
mods.immersiveengineering.Excavator.addMineral("Beryllium", 40, 0.005, ["oreGtExcavatorOreBerylliumOverworld", "oreGtExcavatorOreEmeraldOverworld", "oreGtExcavatorOreThoriumOverworld"], [0.3,0.18,0.12], [0]);
mods.immersiveengineering.Excavator.addMineral("Bornite", 80, 0.005, ["oreGtExcavatorOreBorniteOverworld", "oreGtExcavatorOreChalcociteOverworld", "oreGtExcavatorOreEnargiteOverworld", "oreGtExcavatorOreCopperOverworld"], [0.24,0.24,0.24,0.08], [0]);
mods.immersiveengineering.Excavator.addMineral("Chalcopyrite", 80, 0.005, ["oreGtExcavatorOreChalcopyriteOverworld", "oreGtExcavatorOreIronOverworld", "oreGtExcavatorOrePyriteOverworld", "oreGtExcavatorOreCopperOverworld"], [0.24,0.24,0.24,0.08], [0]);
mods.immersiveengineering.Excavator.addMineral("Coal", 70, 0.005, ["oreGtExcavatorOreLigniteOverworld", "oreGtExcavatorOreCoalOverworld"], [0.3,0.9], [0]);
mods.immersiveengineering.Excavator.addMineral("Diamond", 25, 0.005, ["oreGtExcavatorOreGraphiteOverworld", "oreGtExcavatorOreDiamondOverworld", "oreGtExcavatorOreCoalOverworld"], [0.6,0.2,0.2], [0]);
mods.immersiveengineering.Excavator.addMineral("Galena", 40, 0.005, ["oreGtExcavatorOreGalenaOverworld", "oreGtExcavatorOreSilverOverworld", "oreGtExcavatorOreLeadOverworld"], [0.5,0.25,0.25], [0]);
mods.immersiveengineering.Excavator.addMineral("Iron", 80, 0.005, ["oreGtExcavatorOreBrownLimoniteOverworld", "oreGtExcavatorOreYellowLimoniteOverworld", "oreGtExcavatorOreBandedIronOverworld", "oreGtExcavatorOreMalachiteOverworld"], [0.24,0.24,0.24,0.08], [0]);
mods.immersiveengineering.Excavator.addMineral("Lapis", 50, 0.005, ["oreGtExcavatorOreLazuriteOverworld", "oreGtExcavatorOreSodaliteOverworld", "oreGtExcavatorOreLapisOverworld", "oreGtExcavatorOreCalciteOverworld"], [0.3,0.2,0.35,0.15], [0]);
mods.immersiveengineering.Excavator.addMineral("Lignitecoal", 70, 0.005, ["oreGtExcavatorOreLigniteOverworld", "oreGtExcavatorOreCoalOverworld"], [0.9,0.3], [0]);
mods.immersiveengineering.Excavator.addMineral("Magnetite", 100, 0.005, ["oreGtExcavatorOreMagnetiteOverworld", "oreGtExcavatorOreIronOverworld", "oreGtExcavatorOreVanadiumMagnetiteOverworld", "oreGtExcavatorOreGoldOverworld"], [0.36,0.09,0.09,0.06], [0]);
mods.immersiveengineering.Excavator.addMineral("Manganese", 25, 0.005, ["oreGtExcavatorOreGrossularOverworld", "oreGtExcavatorOreSpessartineOverworld", "oreGtExcavatorOrePyrolusiteOverworld", "oreGtExcavatorOreTantaliteOverworld"], [0.18,0.18,0.18,0.06], [0]);
mods.immersiveengineering.Excavator.addMineral("Molybdenum", 25, 0.005, ["oreGtExcavatorOreWulfeniteOverworld", "oreGtExcavatorOreMolybdeniteOverworld", "oreGtExcavatorOrePowelliteOverworld"], [0.4,0.4,0.2], [0]);
mods.immersiveengineering.Excavator.addMineral("Monazite", 30, 0.005, ["oreGtExcavatorOreBastnasiteOverworld", "oreGtExcavatorOreMonaziteOverworld", "oreGtExcavatorOreNeodymiumOverworld"], [0.48,0.16,0.16], [0]);
mods.immersiveengineering.Excavator.addMineral("Nickel", 65, 0.005, ["oreGtExcavatorOreGarnieriteOverworld", "oreGtExcavatorOreNickelOverworld", "oreGtExcavatorOreCobaltiteOverworld", "oreGtExcavatorOrePentlanditeOverworld"], [0.24,0.24,0.24,0.08], [0]);
mods.immersiveengineering.Excavator.addMineral("Olivine", 55, 0.005, ["oreGtExcavatorOreBentoniteOverworld", "oreGtExcavatorOreMagnesiteOverworld", "oreGtExcavatorOreOlivineOverworld", "oreGtExcavatorOreGlauconiteOverworld"], [0.18,0.18,0.18,0.06], [0]);
mods.immersiveengineering.Excavator.addMineral("Pitchblende", 45, 0.005, ["oreGtExcavatorOrePitchblendeOverworld", "oreGtExcavatorOreUraniniteOverworld", "oreGtExcavatorOreUraniumOverworld"], [0.5,0.4,0.1], [0]);
mods.immersiveengineering.Excavator.addMineral("Platinum", 20, 0.005, ["oreGtExcavatorOrePlatinumOverworld", "oreGtExcavatorOrePalladiumOverworld", "oreGtExcavatorOreIridiumOverworld"], [0.54,0.42,0.24], [0]);
mods.immersiveengineering.Excavator.addMineral("Quartz", 70, 0.005, ["oreGtExcavatorOreQuartziteOverworld", "oreGtExcavatorOreBariteOverworld", "oreGtExcavatorOreCertusQuartzOverworld", "oreGtExcavatorOreTennantiteOverworld"], [0.36,0.2,0.24,0.24], [0]);
mods.immersiveengineering.Excavator.addMineral("Redstone", 70, 0.005, ["oreGtExcavatorOreRedstoneOverworld", "oreGtExcavatorOreRubyOverworld", "oreGtExcavatorOreCinnabarOverworld", "oreGtExcavatorOreChromiteOverworld"], [0.48,0.16,0.16,0.04], [0]);
mods.immersiveengineering.Excavator.addMineral("Salts", 60, 0.005, ["oreGtExcavatorOreSaltOverworld", "oreGtExcavatorOreRockSaltOverworld", "oreGtExcavatorOreLepidoliteOverworld", "oreGtExcavatorOreSpodumeneOverworld"], [0.56,0.49,0.21,0.14], [0]);
mods.immersiveengineering.Excavator.addMineral("Sapphire", 60, 0.005, ["oreGtExcavatorOreAlmandineOverworld", "oreGtExcavatorOrePyropeOverworld", "oreGtExcavatorOreSapphireOverworld", "oreGtExcavatorOreGreenSapphireOverworld"], [0.18,0.18,0.18,0.06], [0]);
mods.immersiveengineering.Excavator.addMineral("Soapstone", 40, 0.005, ["oreGtExcavatorOreSoapstoneOverworld", "oreGtExcavatorOreTalcOverworld", "oreGtExcavatorOreGlauconiteOverworld", "oreGtExcavatorOrePentlanditeOverworld"], [0.25,0.25,0.25,0.25], [0]);
mods.immersiveengineering.Excavator.addMineral("Tenorite", 80, 0.005, ["oreGtExcavatorOreTenoriteOverworld", "oreGtExcavatorOreCopperOverworld", "oreGtExcavatorOreCupriteOverworld"], [0.36,0.12,0.12], [0]);
mods.immersiveengineering.Excavator.addMineral("Tetrahedrite", 70, 0.005, ["oreGtExcavatorOreTetrahedriteOverworld", "oreGtExcavatorOreCopperOverworld", "oreGtExcavatorOreStibniteOverworld"], [0.36,0.12,0.12], [0]);
mods.immersiveengineering.Excavator.addMineral("Tin", 95, 0.005, ["oreGtExcavatorOreTinOverworld", "oreGtExcavatorOreCassiteriteOverworld"], [0.75,0.25], [0]);
mods.immersiveengineering.Excavator.addMineral("Tungstate", 25, 0.005, ["oreGtExcavatorOreScheeliteOverworld", "oreGtExcavatorOreTungstateOverworld", "oreGtExcavatorOreLithiumOverworld"], [0.48,0.16,0.16], [0]);